/** One place for query keys, so invalidation cannot drift from the queries. */
export const queryKeys = {
  me: ["me"] as const,
  oauthConsent: (requestId: string) => ["oauth", "consent", requestId] as const,
  connections: ["oauth", "connections"] as const,
  version: ["version"] as const,
  projects: ["projects"] as const,
  project: (id: string) => ["projects", id] as const,
  members: (projectId: string) => ["projects", projectId, "members"] as const,
  invitations: (projectId: string) => ["projects", projectId, "invitations"] as const,
  entities: (projectId: string) => ["projects", projectId, "entities"] as const,
  features: (projectId: string) => ["projects", projectId, "features"] as const,
  entityAssignments: (projectId: string) => ["projects", projectId, "entity-assignments"] as const,
  currentState: (projectId: string) => ["projects", projectId, "map", "current"] as const,
  track: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "track", params] as const,
  positions: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "positions", params] as const,
  traffic: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "traffic", params] as const,
  traces: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "traces", params] as const,
  trace: (id: string) => ["traces", id] as const,
  sourceEvent: (id: number, ingestedAt: string) => ["source-events", id, ingestedAt] as const,
  audit: (projectId: string | null) => ["audit", projectId ?? "server"] as const,
  devices: (params: Record<string, unknown>) => ["devices", params] as const,
  device: (id: string) => ["devices", id] as const,
  deviceTypes: ["device-types"] as const,
  entityTypes: ["entity-types"] as const,
  metrics: ["metrics"] as const,
  dataSources: ["data-sources"] as const,
  adapters: ["data-sources", "adapters"] as const,
  dataSource: (id: string) => ["data-sources", id] as const,
  identities: (dataSourceId: string) => ["data-sources", dataSourceId, "identities"] as const,
  users: ["admin", "users"] as const,
  serverInvitations: ["admin", "invitations"] as const,
  attentionSummary: ["attention", "summary"] as const,
  unknownIdentities: ["attention", "identities"] as const,
  deadLetters: (topic: string) => ["attention", "dead-letters", topic] as const,
  failedSourceEvents: (status: string) => ["attention", "source-events", status] as const,
  systemHealth: ["system", "health"] as const,
  analyticsSeries: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "analytics", "series", params] as const,
  analyticsRows: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "analytics", "rows", params] as const,
  analyticsMetrics: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "analytics", "metrics", params] as const,
  savedViews: (projectId: string) => ["projects", projectId, "analytics", "saved-views"] as const,
  exports: (projectId: string) => ["projects", projectId, "exports"] as const,
  rules: (projectId: string) => ["projects", projectId, "rules"] as const,
  ruleVersions: (projectId: string, ruleId: string) => ["projects", projectId, "rules", ruleId, "versions"] as const,
  ruleTemplates: (projectId: string) => ["projects", projectId, "rules", "templates"] as const,
  events: (scope: string, params: Record<string, unknown>) => ["events", scope, params] as const,
  event: (scope: string, id: string) => ["events", scope, id] as const,
  alerts: (scope: string, params: Record<string, unknown>) => ["alerts", scope, params] as const,
  automations: (scope: string) => ["automations", scope] as const,
  notificationTargets: (scope: string) => ["notification-targets", scope] as const,
  notificationCapabilities: (scope: string) => ["notification-capabilities", scope] as const,
  deliveries: (scope: string, params: Record<string, unknown>) => ["deliveries", scope, params] as const,
  mapEvents: (projectId: string, hours: number) => ["projects", projectId, "map", "events", hours] as const,
  deviceActions: (deviceId: string) => ["devices", deviceId, "actions"] as const,
  deviceCommands: (deviceId: string) => ["devices", deviceId, "commands"] as const,
  command: (id: string) => ["commands", id] as const,
  projectCommands: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "commands", params] as const,
  downlinkQueue: (deviceId: string) => ["devices", deviceId, "downlink-queue"] as const,
  integrationConnectors: (projectId: string) => ["projects", projectId, "integrations", "connectors"] as const,
  integrations: (projectId: string) => ["projects", projectId, "integrations"] as const,
  integration: (projectId: string, id: string) => ["projects", projectId, "integrations", id] as const,
  integrationDeliveries: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "integration-deliveries", params] as const,
  integrationDelivery: (projectId: string, id: string) => ["projects", projectId, "integration-deliveries", id] as const,
  gateways: (projectId: string, hours: number) => ["projects", projectId, "gateways", hours] as const,
  gateway: (projectId: string, id: string, hours: number) => ["projects", projectId, "gateways", id, hours] as const,
  connectivity: (projectId: string, hours: number) => ["projects", projectId, "connectivity", hours] as const,
  dataSourceCursor: (id: string) => ["data-sources", id, "cursor"] as const,
};
