/** One place for query keys, so invalidation cannot drift from the queries. */
export const queryKeys = {
  me: ["me"] as const,
  version: ["version"] as const,
  projects: ["projects"] as const,
  project: (id: string) => ["projects", id] as const,
  members: (projectId: string) => ["projects", projectId, "members"] as const,
  invitations: (projectId: string) => ["projects", projectId, "invitations"] as const,
  entities: (projectId: string) => ["projects", projectId, "entities"] as const,
  features: (projectId: string) => ["projects", projectId, "features"] as const,
  entityAssignments: (projectId: string) => ["projects", projectId, "entity-assignments"] as const,
  currentState: (projectId: string) => ["projects", projectId, "map", "current"] as const,
  track: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "track", params] as const,
  positions: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "positions", params] as const,
  traffic: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "traffic", params] as const,
  traces: (projectId: string, params: Record<string, unknown>) => ["projects", projectId, "traces", params] as const,
  trace: (id: string) => ["traces", id] as const,
  sourceEvent: (id: number, ingestedAt: string) => ["source-events", id, ingestedAt] as const,
  audit: (projectId: string | null) => ["audit", projectId ?? "server"] as const,
  devices: (params: Record<string, unknown>) => ["devices", params] as const,
  device: (id: string) => ["devices", id] as const,
  deviceTypes: ["device-types"] as const,
  entityTypes: ["entity-types"] as const,
  metrics: ["metrics"] as const,
  dataSources: ["data-sources"] as const,
  dataSource: (id: string) => ["data-sources", id] as const,
  identities: (dataSourceId: string) => ["data-sources", dataSourceId, "identities"] as const,
  users: ["admin", "users"] as const,
  serverInvitations: ["admin", "invitations"] as const,
  attentionSummary: ["attention", "summary"] as const,
  unknownIdentities: ["attention", "identities"] as const,
  deadLetters: (topic: string) => ["attention", "dead-letters", topic] as const,
  failedSourceEvents: (status: string) => ["attention", "source-events", status] as const,
  systemHealth: ["system", "health"] as const,
};
