"""The standard catalogue of entity types (decisions D166 and D167): six types, each holding
the sub-types a park is likely to need, one per vendored icon. Migration 0025 seeds every
server with it, so a new site starts complete and a project hides what it does not want
(`hidden_entity_type_ids` in its settings, D168). Keys are stable; a row an administrator made
by hand under the same key stays as it is (`ON CONFLICT DO NOTHING`).
"""

import json
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class EntityTypeSeed:
    key: str
    label: str
    group_key: str
    icon_key: str
    parent_key: str | None = None


T = EntityTypeSeed

ENTITY_TYPE_SEEDS: tuple[EntityTypeSeed, ...] = (
    T("wildlife", "Wildlife", "tracked", "wildlife.generic"),
    T("person", "People", "tracked", "person.ranger"),
    T("vehicle", "Vehicles", "tracked", "vehicle.4x4"),
    T("infrastructure", "Infrastructure", "infrastructure", "infrastructure.site"),
    T("environmental_sensor", "Environmental sensors", "environmental", "device.weather_station"),
    T("equipment", "Equipment", "equipment", "device.camera_trap"),
    # Sub-types, one per vendored icon; the key is the icon's name.
    T(
        "acoustic_sensor",
        "Acoustic sensor",
        "environmental",
        "device.acoustic_sensor",
        "environmental_sensor",
    ),
    T("camera_trap", "Camera trap", "equipment", "device.camera_trap", "equipment"),
    T("cctv", "CCTV camera", "equipment", "device.cctv", "equipment"),
    T("radio", "Stationary radio", "equipment", "device.radio", "equipment"),
    T("radio_repeater", "Radio repeater", "equipment", "device.radio_repeater", "equipment"),
    T("sensor", "Sensor station", "environmental", "device.sensor", "environmental_sensor"),
    T("video_camera", "Video camera", "equipment", "device.video_camera", "equipment"),
    T(
        "weather_station",
        "Weather station",
        "environmental",
        "device.weather_station",
        "environmental_sensor",
    ),
    T("airstrip", "Airstrip", "infrastructure", "infrastructure.airstrip", "infrastructure"),
    T("bai", "Bai", "infrastructure", "infrastructure.bai", "infrastructure"),
    T("barrier", "Barrier", "infrastructure", "infrastructure.barrier", "infrastructure"),
    T(
        "beehive_fence",
        "Beehive fence",
        "infrastructure",
        "infrastructure.beehive_fence",
        "infrastructure",
    ),
    T("building", "Building", "infrastructure", "infrastructure.building", "infrastructure"),
    T("campsite", "Campsite", "infrastructure", "infrastructure.campsite", "infrastructure"),
    T("clinic", "Clinic", "infrastructure", "infrastructure.clinic", "infrastructure"),
    T("dam", "Dam", "infrastructure", "infrastructure.dam", "infrastructure"),
    T("den", "Den", "infrastructure", "infrastructure.den", "infrastructure"),
    T("door", "Door", "infrastructure", "infrastructure.door", "infrastructure"),
    T(
        "electric_fence",
        "Electric fence",
        "infrastructure",
        "infrastructure.electric_fence",
        "infrastructure",
    ),
    T(
        "evacuation",
        "Evacuation point",
        "infrastructure",
        "infrastructure.evacuation",
        "infrastructure",
    ),
    T(
        "feeding_site",
        "Feeding site",
        "infrastructure",
        "infrastructure.feeding_site",
        "infrastructure",
    ),
    T("fence", "Fence", "infrastructure", "infrastructure.fence", "infrastructure"),
    T(
        "fence_attendant_house",
        "Fence attendant house",
        "infrastructure",
        "infrastructure.fence_attendant_house",
        "infrastructure",
    ),
    T(
        "fence_sensor",
        "Fence sensor",
        "infrastructure",
        "infrastructure.fence_sensor",
        "infrastructure",
    ),
    T("gas_tank", "Gas tank", "infrastructure", "infrastructure.gas_tank", "infrastructure"),
    T("gate", "Gate", "infrastructure", "infrastructure.gate", "infrastructure"),
    T(
        "headquarters",
        "Park headquarters",
        "infrastructure",
        "infrastructure.headquarters",
        "infrastructure",
    ),
    T("helipad", "Helipad", "infrastructure", "infrastructure.helipad", "infrastructure"),
    T("hide", "Hide", "infrastructure", "infrastructure.hide", "infrastructure"),
    T("hospital", "Hospital", "infrastructure", "infrastructure.hospital", "infrastructure"),
    T("house", "House", "infrastructure", "infrastructure.house", "infrastructure"),
    T("jetty", "Jetty", "infrastructure", "infrastructure.jetty", "infrastructure"),
    T("lodge", "Lodge", "infrastructure", "infrastructure.lodge", "infrastructure"),
    T("lodging", "Lodging", "infrastructure", "infrastructure.lodging", "infrastructure"),
    T("mine", "Mine", "infrastructure", "infrastructure.mine", "infrastructure"),
    T("nest", "Nest", "infrastructure", "infrastructure.nest", "infrastructure"),
    T("park_gate", "Park gate", "infrastructure", "infrastructure.park_gate", "infrastructure"),
    T(
        "picnic_spot",
        "Picnic spot",
        "infrastructure",
        "infrastructure.picnic_spot",
        "infrastructure",
    ),
    T(
        "police_station",
        "Police station",
        "infrastructure",
        "infrastructure.police_station",
        "infrastructure",
    ),
    T(
        "pump_station",
        "Pump station",
        "infrastructure",
        "infrastructure.pump_station",
        "infrastructure",
    ),
    T(
        "ranger_post",
        "Ranger post",
        "infrastructure",
        "infrastructure.ranger_post",
        "infrastructure",
    ),
    T(
        "ranger_station",
        "Ranger station",
        "infrastructure",
        "infrastructure.ranger_station",
        "infrastructure",
    ),
    T("repeater", "Radio repeater", "infrastructure", "infrastructure.repeater", "infrastructure"),
    T("roost", "Roost", "infrastructure", "infrastructure.roost", "infrastructure"),
    T(
        "safari_camp",
        "Safari camp",
        "infrastructure",
        "infrastructure.safari_camp",
        "infrastructure",
    ),
    T("settlement", "Settlement", "infrastructure", "infrastructure.settlement", "infrastructure"),
    T(
        "shooting_range",
        "Shooting range",
        "infrastructure",
        "infrastructure.shooting_range",
        "infrastructure",
    ),
    T("site", "Site", "infrastructure", "infrastructure.site", "infrastructure"),
    T(
        "solar_station",
        "Solar station",
        "infrastructure",
        "infrastructure.solar_station",
        "infrastructure",
    ),
    T(
        "spray_race",
        "Cattle spray race",
        "infrastructure",
        "infrastructure.spray_race",
        "infrastructure",
    ),
    T(
        "tourism_center",
        "Tourism centre",
        "infrastructure",
        "infrastructure.tourism_center",
        "infrastructure",
    ),
    T("viewpoint", "Viewpoint", "infrastructure", "infrastructure.viewpoint", "infrastructure"),
    T("village", "Village", "infrastructure", "infrastructure.village", "infrastructure"),
    T(
        "water_gauge",
        "Water gauge",
        "environmental",
        "infrastructure.water_gauge",
        "environmental_sensor",
    ),
    T(
        "water_point",
        "Water point",
        "infrastructure",
        "infrastructure.water_point",
        "infrastructure",
    ),
    T("water_pump", "Water pump", "infrastructure", "infrastructure.water_pump", "infrastructure"),
    T("water_tank", "Water tank", "infrastructure", "infrastructure.water_tank", "infrastructure"),
    T(
        "wind_turbine",
        "Wind turbine",
        "infrastructure",
        "infrastructure.wind_turbine",
        "infrastructure",
    ),
    T("windmill", "Windmill", "infrastructure", "infrastructure.windmill", "infrastructure"),
    T("dog_team", "Dog team", "tracked", "person.dog_team", "person"),
    T("fence_attendant", "Fence attendant", "tracked", "person.fence_attendant", "person"),
    T("manager", "Manager", "tracked", "person.manager", "person"),
    T("patrol_team", "Patrol team", "tracked", "person.patrol_team", "person"),
    T("ranger", "Ranger", "tracked", "person.ranger", "person"),
    T("ranger_team", "Ranger team", "tracked", "person.ranger_team", "person"),
    T("researcher", "Researcher", "tracked", "person.researcher", "person"),
    T("scout", "Scout", "tracked", "person.scout", "person"),
    T("four_by_four", "4x4", "tracked", "vehicle.4x4", "vehicle"),
    T("balloon", "Hot air balloon", "tracked", "vehicle.balloon", "vehicle"),
    T("bicycle", "Bicycle", "tracked", "vehicle.bicycle", "vehicle"),
    T("boat", "Boat", "tracked", "vehicle.boat", "vehicle"),
    T("car", "Car", "tracked", "vehicle.car", "vehicle"),
    T("drone", "Drone", "tracked", "vehicle.drone", "vehicle"),
    T("dump_truck", "Dump truck", "tracked", "vehicle.dump_truck", "vehicle"),
    T("excavator", "Excavator", "tracked", "vehicle.excavator", "vehicle"),
    T("helicopter", "Helicopter", "tracked", "vehicle.helicopter", "vehicle"),
    T("motorcycle", "Motorcycle", "tracked", "vehicle.motorcycle", "vehicle"),
    T("plane", "Aircraft", "tracked", "vehicle.plane", "vehicle"),
    T("quad", "Quad bike", "tracked", "vehicle.quad", "vehicle"),
    T("quadcopter", "Quadcopter", "tracked", "vehicle.quadcopter", "vehicle"),
    T("ranger_boat", "Ranger boat", "tracked", "vehicle.ranger_boat", "vehicle"),
    T("security", "Security vehicle", "tracked", "vehicle.security", "vehicle"),
    T("tourist", "Tourist vehicle", "tracked", "vehicle.tourist", "vehicle"),
    T("tractor", "Tractor", "tracked", "vehicle.tractor", "vehicle"),
    T("truck", "Truck", "tracked", "vehicle.truck", "vehicle"),
    T("van", "Van", "tracked", "vehicle.van", "vehicle"),
    T("aardvark", "Aardvark", "tracked", "wildlife.aardvark", "wildlife"),
    T("addax", "Addax", "tracked", "wildlife.addax", "wildlife"),
    T("albatross", "Albatross", "tracked", "wildlife.albatross", "wildlife"),
    T("antelope", "Antelope", "tracked", "wildlife.antelope", "wildlife"),
    T("arctic_fox", "Arctic fox", "tracked", "wildlife.arctic_fox", "wildlife"),
    T("asian_elephant", "Asian elephant", "tracked", "wildlife.asian_elephant", "wildlife"),
    T("baboon", "Baboon", "tracked", "wildlife.baboon", "wildlife"),
    T("badger", "Badger", "tracked", "wildlife.badger", "wildlife"),
    T("barbary_sheep", "Barbary sheep", "tracked", "wildlife.barbary_sheep", "wildlife"),
    T("bear", "Bear", "tracked", "wildlife.bear", "wildlife"),
    T("bearded_vulture", "Bearded vulture", "tracked", "wildlife.bearded_vulture", "wildlife"),
    T("bighorn_sheep", "Bighorn sheep", "tracked", "wildlife.bighorn_sheep", "wildlife"),
    T("bird", "Bird", "tracked", "wildlife.bird", "wildlife"),
    T("bison", "Bison", "tracked", "wildlife.bison", "wildlife"),
    T("black_bear", "Black bear", "tracked", "wildlife.black_bear", "wildlife"),
    T("black_vulture", "Black vulture", "tracked", "wildlife.black_vulture", "wildlife"),
    T("bobcat", "Bobcat", "tracked", "wildlife.bobcat", "wildlife"),
    T("bovid", "Bovid", "tracked", "wildlife.bovid", "wildlife"),
    T("brown_bear", "Brown bear", "tracked", "wildlife.brown_bear", "wildlife"),
    T("brown_hyena", "Brown hyena", "tracked", "wildlife.brown_hyena", "wildlife"),
    T("buffalo", "Buffalo", "tracked", "wildlife.buffalo", "wildlife"),
    T("bull", "Bull", "tracked", "wildlife.bull", "wildlife"),
    T("camel", "Camel", "tracked", "wildlife.camel", "wildlife"),
    T("canid", "Canid", "tracked", "wildlife.canid", "wildlife"),
    T("cape_vulture", "Cape vulture", "tracked", "wildlife.cape_vulture", "wildlife"),
    T("chamois", "Chamois", "tracked", "wildlife.chamois", "wildlife"),
    T("cheetah", "Cheetah", "tracked", "wildlife.cheetah", "wildlife"),
    T("chimpanzee", "Chimpanzee", "tracked", "wildlife.chimpanzee", "wildlife"),
    T(
        "cinereous_vulture",
        "Cinereous vulture",
        "tracked",
        "wildlife.cinereous_vulture",
        "wildlife",
    ),
    T("cougar", "Cougar", "tracked", "wildlife.cougar", "wildlife"),
    T("cow", "Cow", "tracked", "wildlife.cow", "wildlife"),
    T("crane", "Crane", "tracked", "wildlife.crane", "wildlife"),
    T("crocodile", "Crocodile", "tracked", "wildlife.crocodile", "wildlife"),
    T("deer", "Deer", "tracked", "wildlife.deer", "wildlife"),
    T("demoiselle_crane", "Demoiselle crane", "tracked", "wildlife.demoiselle_crane", "wildlife"),
    T("dog", "Dog", "tracked", "wildlife.dog", "wildlife"),
    T("donkey", "Donkey", "tracked", "wildlife.donkey", "wildlife"),
    T("dugong", "Dugong", "tracked", "wildlife.dugong", "wildlife"),
    T("duiker", "Duiker", "tracked", "wildlife.duiker", "wildlife"),
    T("eagle_owl", "Eagle owl", "tracked", "wildlife.eagle_owl", "wildlife"),
    T("eland", "Eland", "tracked", "wildlife.eland", "wildlife"),
    T("elephant", "Elephant", "tracked", "wildlife.elephant", "wildlife"),
    T("elk", "Elk", "tracked", "wildlife.elk", "wildlife"),
    T("eurasian_lynx", "Eurasian lynx", "tracked", "wildlife.eurasian_lynx", "wildlife"),
    T("european_roller", "European roller", "tracked", "wildlife.european_roller", "wildlife"),
    T("falcon", "Falcon", "tracked", "wildlife.falcon", "wildlife"),
    T("fallow_deer", "Fallow deer", "tracked", "wildlife.fallow_deer", "wildlife"),
    T("feline", "Feline", "tracked", "wildlife.feline", "wildlife"),
    T("fish", "Fish", "tracked", "wildlife.fish", "wildlife"),
    T("flamingo", "Flamingo", "tracked", "wildlife.flamingo", "wildlife"),
    T("forest_elephant", "Forest elephant", "tracked", "wildlife.forest_elephant", "wildlife"),
    T("frog", "Frog", "tracked", "wildlife.frog", "wildlife"),
    T("gerenuk", "Gerenuk", "tracked", "wildlife.gerenuk", "wildlife"),
    T("gibbon", "Gibbon", "tracked", "wildlife.gibbon", "wildlife"),
    T("giraffe", "Giraffe", "tracked", "wildlife.giraffe", "wildlife"),
    T("goat", "Goat", "tracked", "wildlife.goat", "wildlife"),
    T("goose", "Goose", "tracked", "wildlife.goose", "wildlife"),
    T("gorilla", "Gorilla", "tracked", "wildlife.gorilla", "wildlife"),
    T("grants_gazelle", "Grant's gazelle", "tracked", "wildlife.grants_gazelle", "wildlife"),
    T(
        "great_white_shark",
        "Great white shark",
        "tracked",
        "wildlife.great_white_shark",
        "wildlife",
    ),
    T("greater_kudu", "Greater kudu", "tracked", "wildlife.greater_kudu", "wildlife"),
    T("grevys_zebra", "Grevy's zebra", "tracked", "wildlife.grevys_zebra", "wildlife"),
    T("griffon_vulture", "Griffon vulture", "tracked", "wildlife.griffon_vulture", "wildlife"),
    T("gull", "Gull", "tracked", "wildlife.gull", "wildlife"),
    T("hare", "Hare", "tracked", "wildlife.hare", "wildlife"),
    T("hartebeest", "Hartebeest", "tracked", "wildlife.hartebeest", "wildlife"),
    T("hawk", "Hawk", "tracked", "wildlife.hawk", "wildlife"),
    T("hippo", "Hippo", "tracked", "wildlife.hippo", "wildlife"),
    T("hirola", "Hirola", "tracked", "wildlife.hirola", "wildlife"),
    T("hooded_vulture", "Hooded vulture", "tracked", "wildlife.hooded_vulture", "wildlife"),
    T("hornbill", "Hornbill", "tracked", "wildlife.hornbill", "wildlife"),
    T("horse", "Horse", "tracked", "wildlife.horse", "wildlife"),
    T("hyena", "Hyena", "tracked", "wildlife.hyena", "wildlife"),
    T("ibex", "Ibex", "tracked", "wildlife.ibex", "wildlife"),
    T("impala", "Impala", "tracked", "wildlife.impala", "wildlife"),
    T("jackal", "Jackal", "tracked", "wildlife.jackal", "wildlife"),
    T("jaguar", "Jaguar", "tracked", "wildlife.jaguar", "wildlife"),
    T("koala", "Koala", "tracked", "wildlife.koala", "wildlife"),
    T("kulan", "Kulan", "tracked", "wildlife.kulan", "wildlife"),
    T(
        "lappet_faced_vulture",
        "Lappet-faced vulture",
        "tracked",
        "wildlife.lappet_faced_vulture",
        "wildlife",
    ),
    T("leopard", "Leopard", "tracked", "wildlife.leopard", "wildlife"),
    T("lesser_kudu", "Lesser kudu", "tracked", "wildlife.lesser_kudu", "wildlife"),
    T("lion", "Lion", "tracked", "wildlife.lion", "wildlife"),
    T("livestock", "Livestock", "tracked", "wildlife.livestock", "wildlife"),
    T("lynx", "Lynx", "tracked", "wildlife.lynx", "wildlife"),
    T("lyrebird", "Lyrebird", "tracked", "wildlife.lyrebird", "wildlife"),
    T("macaw", "Macaw", "tracked", "wildlife.macaw", "wildlife"),
    T("mammal", "Mammal", "tracked", "wildlife.mammal", "wildlife"),
    T("manatee", "Manatee", "tracked", "wildlife.manatee", "wildlife"),
    T("manta_ray", "Manta ray", "tracked", "wildlife.manta_ray", "wildlife"),
    T("marine", "Marine mammal", "tracked", "wildlife.marine", "wildlife"),
    T("martial_eagle", "Martial eagle", "tracked", "wildlife.martial_eagle", "wildlife"),
    T("meerkat", "Meerkat", "tracked", "wildlife.meerkat", "wildlife"),
    T("monkey", "Monkey", "tracked", "wildlife.monkey", "wildlife"),
    T("moose", "Moose", "tracked", "wildlife.moose", "wildlife"),
    T("mule", "Mule", "tracked", "wildlife.mule", "wildlife"),
    T("mule_deer", "Mule deer", "tracked", "wildlife.mule_deer", "wildlife"),
    T("muskox", "Muskox", "tracked", "wildlife.muskox", "wildlife"),
    T("ocelot", "Ocelot", "tracked", "wildlife.ocelot", "wildlife"),
    T("opossum", "Opossum", "tracked", "wildlife.opossum", "wildlife"),
    T("orangutan", "Orangutan", "tracked", "wildlife.orangutan", "wildlife"),
    T("orca", "Orca", "tracked", "wildlife.orca", "wildlife"),
    T("ostrich", "Ostrich", "tracked", "wildlife.ostrich", "wildlife"),
    T("pangolin", "Pangolin", "tracked", "wildlife.pangolin", "wildlife"),
    T("passerine", "Passerine", "tracked", "wildlife.passerine", "wildlife"),
    T("peccary", "Peccary", "tracked", "wildlife.peccary", "wildlife"),
    T("pelican", "Pelican", "tracked", "wildlife.pelican", "wildlife"),
    T("petrel", "Petrel", "tracked", "wildlife.petrel", "wildlife"),
    T("polar_bear", "Polar bear", "tracked", "wildlife.polar_bear", "wildlife"),
    T("primate", "Primate", "tracked", "wildlife.primate", "wildlife"),
    T("pronghorn", "Pronghorn", "tracked", "wildlife.pronghorn", "wildlife"),
    T("rabbit", "Rabbit", "tracked", "wildlife.rabbit", "wildlife"),
    T("raccoon", "Raccoon", "tracked", "wildlife.raccoon", "wildlife"),
    T("raptor", "Bird of prey", "tracked", "wildlife.raptor", "wildlife"),
    T("raven", "Raven", "tracked", "wildlife.raven", "wildlife"),
    T("red_deer", "Red deer", "tracked", "wildlife.red_deer", "wildlife"),
    T("red_panda", "Red panda", "tracked", "wildlife.red_panda", "wildlife"),
    T("reptile", "Reptile", "tracked", "wildlife.reptile", "wildlife"),
    T(
        "reptiles_amphibians",
        "Reptiles and amphibians",
        "tracked",
        "wildlife.reptiles_amphibians",
        "wildlife",
    ),
    T("rhino", "Rhino", "tracked", "wildlife.rhino", "wildlife"),
    T("roan", "Roan antelope", "tracked", "wildlife.roan", "wildlife"),
    T("sable", "Sable antelope", "tracked", "wildlife.sable", "wildlife"),
    T("scimitar_oryx", "Scimitar oryx", "tracked", "wildlife.scimitar_oryx", "wildlife"),
    T("sea_lion", "Sea lion", "tracked", "wildlife.sea_lion", "wildlife"),
    T("secretary_bird", "Secretary bird", "tracked", "wildlife.secretary_bird", "wildlife"),
    T("serval", "Serval", "tracked", "wildlife.serval", "wildlife"),
    T("shark", "Shark", "tracked", "wildlife.shark", "wildlife"),
    T("sheep", "Sheep", "tracked", "wildlife.sheep", "wildlife"),
    T("shoebill", "Shoebill", "tracked", "wildlife.shoebill", "wildlife"),
    T("sloth", "Sloth", "tracked", "wildlife.sloth", "wildlife"),
    T("snowy_owl", "Snowy owl", "tracked", "wildlife.snowy_owl", "wildlife"),
    T("spotted_hyena", "Spotted hyena", "tracked", "wildlife.spotted_hyena", "wildlife"),
    T("swift_fox", "Swift fox", "tracked", "wildlife.swift_fox", "wildlife"),
    T("tapir", "Tapir", "tracked", "wildlife.tapir", "wildlife"),
    T("tauros", "Tauros", "tracked", "wildlife.tauros", "wildlife"),
    T("tiang", "Tiang", "tracked", "wildlife.tiang", "wildlife"),
    T("topi", "Topi", "tracked", "wildlife.topi", "wildlife"),
    T("tortoise", "Tortoise", "tracked", "wildlife.tortoise", "wildlife"),
    T("tree_kangaroo", "Tree kangaroo", "tracked", "wildlife.tree_kangaroo", "wildlife"),
    T("turtle", "Turtle", "tracked", "wildlife.turtle", "wildlife"),
    T("vicuna", "Vicuña", "tracked", "wildlife.vicuna", "wildlife"),
    T("vulture", "Vulture", "tracked", "wildlife.vulture", "wildlife"),
    T("warthog", "Warthog", "tracked", "wildlife.warthog", "wildlife"),
    T("waterbuck", "Waterbuck", "tracked", "wildlife.waterbuck", "wildlife"),
    T("whale", "Whale", "tracked", "wildlife.whale", "wildlife"),
    T("whale_shark", "Whale shark", "tracked", "wildlife.whale_shark", "wildlife"),
    T(
        "white_backed_vulture",
        "White-backed vulture",
        "tracked",
        "wildlife.white_backed_vulture",
        "wildlife",
    ),
    T("white_rhino", "White rhino", "tracked", "wildlife.white_rhino", "wildlife"),
    T("wild_boar", "Wild boar", "tracked", "wildlife.wild_boar", "wildlife"),
    T("wild_dog", "Wild dog", "tracked", "wildlife.wild_dog", "wildlife"),
    T("wild_horse", "Wild horse", "tracked", "wildlife.wild_horse", "wildlife"),
    T("wildebeest", "Wildebeest", "tracked", "wildlife.wildebeest", "wildlife"),
    T("wolf", "Wolf", "tracked", "wildlife.wolf", "wildlife"),
    T("zebra", "Zebra", "tracked", "wildlife.zebra", "wildlife"),
)


def seed_sql() -> list[str]:
    """Two INSERT statements for a migration: the types, then the sub-types with their parent
    looked up by key. Existing rows are left untouched."""
    parents = [s for s in ENTITY_TYPE_SEEDS if s.parent_key is None]
    children = [s for s in ENTITY_TYPE_SEEDS if s.parent_key is not None]
    columns = "(key, label, group_key, icon_key, attribute_schema, parent_id)"
    parent_values = ",\n".join(
        f"({_literal(s.key)}, {_literal(s.label)}, {_literal(s.group_key)}, "
        f"{_literal(s.icon_key)}, '{{}}'::jsonb, NULL)"
        for s in parents
    )
    child_values = ",\n".join(
        f"({_literal(s.key)}, {_literal(s.label)}, {_literal(s.group_key)}, "
        f"{_literal(s.icon_key)}, '{{}}'::jsonb, "
        f"(SELECT id FROM entity_types WHERE key = {_literal(s.parent_key or '')}))"
        for s in children
    )
    return [
        f"INSERT INTO entity_types {columns} VALUES\n{parent_values}\nON CONFLICT (key) DO NOTHING",
        f"INSERT INTO entity_types {columns} VALUES\n{child_values}\nON CONFLICT (key) DO NOTHING",
    ]


def _literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def as_json() -> str:
    """The catalogue for tests and tooling."""
    return json.dumps([s.__dict__ for s in ENTITY_TYPE_SEEDS])
