"""Driver contract (architecture 9 and 25.3).

A driver turns a source event into decoded records and declares, per record type, which
timestamp is canonical. It also owns the canonical key that deduplicates the same device record
delivered over several paths, and (phase 6) the encoding of control actions.
"""

import hashlib
import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from typing import Any, ClassVar, Protocol

from shared.enums import Severity


class TimestampSemantics(StrEnum):
    """Where the canonical time of a record comes from."""

    DEVICE_TIME = "device_time"  # embedded in the payload, generated by the device
    NETWORK_TIME = "network_time"  # the device sends no clock; the network receive time is best


@dataclass(slots=True)
class DecodedPosition:
    time: datetime
    latitude: float
    longitude: float
    record_type: str = "gnss"
    altitude_m: float | None = None
    speed_mps: float | None = None
    heading_deg: float | None = None
    accuracy_m: float | None = None
    satellites: int | None = None
    attributes: dict[str, Any] = field(default_factory=dict)
    fingerprint: str | None = None


@dataclass(slots=True)
class DecodedMeasurement:
    time: datetime
    metric_key: str
    value: float | bool | str | dict[str, Any]
    record_type: str = "measurement"
    fingerprint: str | None = None


@dataclass(slots=True)
class DecodedState:
    time: datetime
    state: dict[str, Any]
    record_type: str = "state"


@dataclass(slots=True)
class DecodedEvent:
    time: datetime
    event_type: str
    title: str
    severity: Severity = Severity.INFO
    context: dict[str, Any] = field(default_factory=dict)
    record_type: str = "event"
    latitude: float | None = None
    longitude: float | None = None
    description: str | None = None


@dataclass(slots=True)
class DecodedRecords:
    positions: list[DecodedPosition] = field(default_factory=list)
    measurements: list[DecodedMeasurement] = field(default_factory=list)
    states: list[DecodedState] = field(default_factory=list)
    events: list[DecodedEvent] = field(default_factory=list)
    decoder_version: str = "1"

    @property
    def empty(self) -> bool:
        return not (self.positions or self.measurements or self.states or self.events)


@dataclass(frozen=True, slots=True)
class SourceEventData:
    """What a driver may see of a source event.

    `payload` is the provider message as stored. For LoRaWAN uplinks the decoder also extracts
    the application frame: `frame` (the decoded bytes) and `f_port`. Drivers of LoRaWAN devices
    work on those two and never on provider fields.
    """

    id: int
    event_type: str
    payload: dict[str, Any]
    provider_metadata: dict[str, Any]
    network_received_at: datetime | None
    ingested_at: datetime
    device_attributes: dict[str, Any]
    device_type_settings: dict[str, Any]
    frame: bytes | None = None
    f_port: int | None = None


DEFAULT_DECODABLE_EVENT_TYPES: frozenset[str] = frozenset({"uplink"})


class DeviceDriver(Protocol):
    key: ClassVar[str]
    label: ClassVar[str]
    capabilities: ClassVar[frozenset[str]]
    timestamp_semantics: ClassVar[dict[str, TimestampSemantics]]
    decodable_event_types: ClassVar[frozenset[str]]
    # Optional: `control_actions: ClassVar[dict[str, ControlAction]]` (shared.control.actions).
    # Drivers without it accept no commands.

    def decode(self, event: SourceEventData) -> DecodedRecords: ...


def lorawan_frame(
    payload: dict[str, Any], provider_metadata: dict[str, Any]
) -> tuple[bytes | None, int | None]:
    """The application payload of a LoRaWAN uplink as stored by the adapter: base64 `data` and
    `fPort` in the payload (ChirpStack shape) or `frame_hex` and `f_port` in provider metadata
    (other adapters normalize to this)."""
    import base64

    f_port = provider_metadata.get("f_port")
    if f_port is None:
        f_port = payload.get("fPort")
    if "frame_hex" in provider_metadata:
        return bytes.fromhex(str(provider_metadata["frame_hex"])), int(
            f_port
        ) if f_port is not None else None
    data = payload.get("data")
    if isinstance(data, str):
        try:
            return base64.b64decode(data, validate=True), int(
                f_port
            ) if f_port is not None else None
        except (ValueError, TypeError):
            return None, int(f_port) if f_port is not None else None
    return None, int(f_port) if f_port is not None else None


def canonical_key(
    device_id: uuid.UUID, time: datetime, record_type: str, extra: str | None = None
) -> str:
    """Device + canonical time + record type (+ fingerprint or metric) identifies one device record
    however many times it is delivered (ADR 0008)."""
    key = f"{device_id}:{time.astimezone().isoformat()}:{record_type}"
    return f"{key}:{extra}" if extra else key


def fingerprint(value: Any) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, default=str).encode()).hexdigest()[:16]
