"""Driver contract (architecture 9 and 25.3).

A driver turns a source event into decoded records and declares, per record type, which
timestamp is canonical. It also owns the canonical key that deduplicates the same device record
delivered over several paths, and (phase 6) the encoding of control actions.
"""

import hashlib
import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from typing import Any, ClassVar, Protocol

from shared.enums import Severity


class TimestampSemantics(StrEnum):
    """Where the canonical time of a record comes from."""

    DEVICE_TIME = "device_time"  # embedded in the payload, generated by the device
    NETWORK_TIME = "network_time"  # the device sends no clock; the network receive time is best


@dataclass(slots=True)
class DecodedPosition:
    time: datetime
    latitude: float
    longitude: float
    record_type: str = "gnss"
    altitude_m: float | None = None
    speed_mps: float | None = None
    heading_deg: float | None = None
    accuracy_m: float | None = None
    satellites: int | None = None
    attributes: dict[str, Any] = field(default_factory=dict)
    fingerprint: str | None = None


@dataclass(slots=True)
class DecodedMeasurement:
    time: datetime
    metric_key: str
    value: float | bool | str | dict[str, Any]
    record_type: str = "measurement"
    fingerprint: str | None = None


@dataclass(slots=True)
class DecodedState:
    time: datetime
    state: dict[str, Any]
    record_type: str = "state"


@dataclass(slots=True)
class DecodedEvent:
    time: datetime
    event_type: str
    title: str
    severity: Severity = Severity.INFO
    context: dict[str, Any] = field(default_factory=dict)
    record_type: str = "event"


@dataclass(slots=True)
class DecodedRecords:
    positions: list[DecodedPosition] = field(default_factory=list)
    measurements: list[DecodedMeasurement] = field(default_factory=list)
    states: list[DecodedState] = field(default_factory=list)
    events: list[DecodedEvent] = field(default_factory=list)
    decoder_version: str = "1"

    @property
    def empty(self) -> bool:
        return not (self.positions or self.measurements or self.states or self.events)


@dataclass(frozen=True, slots=True)
class SourceEventData:
    """What a driver may see of a source event."""

    id: int
    event_type: str
    payload: dict[str, Any]
    provider_metadata: dict[str, Any]
    network_received_at: datetime | None
    ingested_at: datetime
    device_attributes: dict[str, Any]
    device_type_settings: dict[str, Any]


class DeviceDriver(Protocol):
    key: ClassVar[str]
    label: ClassVar[str]
    capabilities: ClassVar[frozenset[str]]
    timestamp_semantics: ClassVar[dict[str, TimestampSemantics]]

    def decode(self, event: SourceEventData) -> DecodedRecords: ...


def canonical_key(
    device_id: uuid.UUID, time: datetime, record_type: str, extra: str | None = None
) -> str:
    """Device + canonical time + record type (+ fingerprint or metric) identifies one device record
    however many times it is delivered (ADR 0008)."""
    key = f"{device_id}:{time.astimezone().isoformat()}:{record_type}"
    return f"{key}:{extra}" if extra else key


def fingerprint(value: Any) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, default=str).encode()).hexdigest()[:16]
