"""ORM models. Import this package so every table is registered on `Base.metadata`."""

from shared.models.access import (
    AuditLog,
    Invitation,
    Organization,
    Project,
    ProjectMembership,
    User,
)
from shared.models.analytics import ExportJob, SavedView
from shared.models.base import Base
from shared.models.control import Command, CommandExecution
from shared.models.domain import (
    DataSource,
    DataSourceProjectScope,
    Device,
    DeviceEntityAssignment,
    DeviceProjectAssignment,
    DeviceType,
    Entity,
    EntityType,
    ExternalIdentity,
    Feature,
    Metric,
)
from shared.models.events import (
    ActionDelivery,
    Alert,
    Automation,
    Event,
    NotificationTarget,
    Rule,
    RuleState,
    RuleVersion,
)
from shared.models.integrations import Integration, IntegrationDelivery
from shared.models.network import DataSourceCursor, Gateway
from shared.models.timeseries import (
    HYPERTABLES,
    ConnectivityState,
    DeviceCurrentState,
    DeviceStateHistory,
    EntityCurrentState,
    GatewayReception,
    Measurement,
    Position,
    SourceDelivery,
    SourceEvent,
)
from shared.models.trace import ApplicationError, ProcessingStep, ProcessingTrace

__all__ = [
    "HYPERTABLES",
    "ActionDelivery",
    "Alert",
    "ApplicationError",
    "AuditLog",
    "Automation",
    "Base",
    "Command",
    "CommandExecution",
    "ConnectivityState",
    "DataSource",
    "DataSourceCursor",
    "DataSourceProjectScope",
    "Device",
    "DeviceCurrentState",
    "DeviceEntityAssignment",
    "DeviceProjectAssignment",
    "DeviceStateHistory",
    "DeviceType",
    "Entity",
    "EntityCurrentState",
    "EntityType",
    "Event",
    "ExportJob",
    "ExternalIdentity",
    "Feature",
    "Gateway",
    "GatewayReception",
    "Integration",
    "IntegrationDelivery",
    "Invitation",
    "Measurement",
    "Metric",
    "NotificationTarget",
    "Organization",
    "Position",
    "ProcessingStep",
    "ProcessingTrace",
    "Project",
    "ProjectMembership",
    "Rule",
    "RuleState",
    "RuleVersion",
    "SavedView",
    "SourceDelivery",
    "SourceEvent",
    "User",
]
